#define SFX_AMBULANCE	0
#define SFX_BOOM	1
#define MOD_KEYG_SUBTONAL	0
#define MOD_PURPLE_MOTION_INSPIRATION	1
#define MOD_REZ_MONDAY	2
#define MSL_NSONGS	3
#define MSL_NSAMPS	67
#define MSL_BANKSIZE	70
